### PR TITLE
584 refactoring training saving result

### LINKED ISSUE #584: when AlgorithmSource type is changed from `vcs` to `objectStorage`, commit ID for result remains
**Description**
when AlgorithmSource type for the same training is changed from `vcs` to `objectStorage`, commit ID for result remains in the run for `objectStorage` type.

**Precondition**
* Add model training files to bucket for `objectStorage` AlgorithmSource type:
  ```
  gsutil rsync -r -x ".*DS_Store$" odahu-examples/mlflow/sklearn/wine  gs://<bucket name>/my-model/wine/odahu
  ```

**Manifests**
1. [create_train-odahu-diff-vcs-object-storage.txt](https://github.com/odahu/odahu-flow/files/6538305/create_train-odahu-diff-vcs-object-storage.txt)
2. [update_train-odahu-diff-vcs-object-storage.txt](https://github.com/odahu/odahu-flow/files/6538307/update_train-odahu-diff-vcs-object-storage.txt)

**Steps to Reproduce:**
1. Create model training with `vcs` AlgorithmSource type and wait until succeeds.
2. Update training from step (1) by changing AlgorithmSource type to `objectStorage`.
3. Notice that in the Result/Status commit ID is present for both runs.

**Actual result**
when AlgorithmSource type for the same training is changed from `vcs` to `objectStorage`, commit ID for result remains in the run for `objectStorage` type.

**Expected result**
The commit ID should be present only for the result of training run with `vcs` AlgorithmSource type.

**Attachments**
image

### PR DESCRIPTION
**Pull request by lev-titov**
issue https://github.com/odahu/odahu-flow/issues/584

### CODE REVIEW

File: packages/operator/pkg/trainer/trainer.go [hunk 1]
```diff
@@ -254,6 +273,15 @@ func (mt *ModelTrainer) DownloadAlgorithm(k8sTraining *training.K8sTrainer) erro
...
 		}
+		commit := &CommitInfo{
+			CommitID: commitID,
+		}
+		fileBytes, err := json.Marshal(commit)
+		if err != nil {
+			return err
+		}
+
+		_ = ioutil.WriteFile(commitInfoFile, fileBytes, 0644)
```
Comment (keshamin) [inline packages/operator/pkg/trainer/trainer.go]: For easier debugging in future, I'd check the returned error with logging if one occurs.

File: packages/operator/pkg/trainer/trainer.go [hunk 2]
```diff
@@ -191,11 +191,30 @@ func (mt *ModelTrainer) SaveResult() error {
 		return err
 	}
 
+	commit := &CommitInfo{}
+	if k8sTraining.AlgorithmSourceConnection.Spec.Type == connection.GITType {
+		commitJsonFile, err := os.Open(commitInfoFile)
```
Comment (keshamin) [inline packages/operator/pkg/trainer/trainer.go]: I guess `ioutil.ReadFile()` to make it a bit shorter

**Review by keshamin — APPROVED** [review]

**Review by BPylypenko — APPROVED** [review]
