### PR TITLE
Not look for Packaging integration if .Spec.IntegrationName is empty

### LINKED ISSUE #438: checks if pack integration exists when I hadn't passed it
**description**
if I pass an empty `integrationName` or don't specify it at all, then I get an error:
> Validation of model packaging is failed: entity "" is not found; you should specify artifactName; integration name must be nonempty

It shows that the `integration name` must be non-empty while trying to find packaging integration:
> entity "" is not found

**specification**
[packaging_no_required_params.txt](https://github.com/odahu/odahu-flow/files/5604709/packaging_no_required_params.txt)

**to reproduce**
1. run `odahuflowctl pack create -f packaging_no_required_params.txt`

**expected behavior**
should only show that `integration name must be nonempty`

**actual behavior**
shows that `integration name must be nonempty` and `entity "" is not found`

### PR DESCRIPTION
**Pull request by vlad-tokarev**
If ModelPackaging.Spec.IntegrationName is empty we shouldn't try to find this integration at all when we validate ModelPackaging

closes #438

### CODE REVIEW

**Review by karbyshevds — APPROVED** [review]

File: packages/operator/pkg/apiserver/routes/v1/packaging/model_packaging_validation.go [hunk 1]
```diff
@@ -107,10 +107,13 @@ func (mpv *MpValidator) validateMainParameters(mp *packaging.ModelPackaging) (er
...
+	// If image is empty then set image from Packaging Integration
 	if len(mp.Spec.Image) == 0 {
-		packagingIntegration, k8sErr := mpv.piRepo.GetPackagingIntegration(mp.Spec.IntegrationName)
-		if k8sErr != nil {
-			err = multierr.Append(err, k8sErr)
+		packagingIntegration, getPiErr := mpv.piRepo.GetPackagingIntegration(mp.Spec.IntegrationName)
+		if getPiErr != nil {
+			logMP.Info(
+				"Unable to extract default image from Packaging integration because it is empty",
+			)
```
Comment (keshamin) [inline packages/operator/pkg/apiserver/routes/v1/packaging/model_packaging_validation.go]:
```suggestion
		if len(mp.Spec.IntegrationName) == 0 {
			err = multierr.Append(err, errors.New("Model Packaging must have either Image or PackagingIntegration"))
		}
		packagingIntegration, getPiErr := mpv.piRepo.GetPackagingIntegration(mp.Spec.IntegrationName)
		if getPiErr != nil {
			logMP.Error(getPiErr, "Unable to get Packaging integration from repository")
			panic(getPiErr)
```
1. I suggest to explicitly check if `mp.Spec.IntegrationName` is empty, because it is not the only reason the repository can return error. 
2. When we know that `mp.Spec.IntegrationName` is **not empty** and still we get error from repo, it is really bad unexpected condition of the system. Basically it is 500 http status, so we can either `panic`, or handle this case in other way you like. 
What do you think?

Comment (vlad-tokarev) [reply packages/operator/pkg/apiserver/routes/v1/packaging/model_packaging_validation.go:116]: 1. I agree that we should check error using .IsNotFoundError()

**Review by keshamin — APPROVED** [review]
