### PR TITLE
601 fixing missing createdAT field

### LINKED ISSUE #601: when the connection is updated the `updatedAt` field stays the same
**Description**
when the connection is updated the `updatedAt` field stays the same.

**Manifest:**
[connection.txt](https://github.com/odahu/odahu-flow/files/6818576/connection.txt)

**Steps to Reproduce:**
1. Create connection: `odahuflowctl conn create -f connection.txt`
2. Update connection: `odahuflowctl conn edit -f connection.txt`
3. Notice that output for updated connection shows that `createdAt: '0001-01-01T00:00:00Z'` and real `updatedAt` time in UTC.
4. Get connection: `odahuflowctl conn get --id test-connection`
5. Notice that `createdAt` & `updatedAt` fields are the same as during creation.

**Actual result**
`updatedAt` connection field doesn't update (shows the same value as `createAt` field). 

**Expected result**
`createdAt` and `updatedAt` fields should show the real values.

**Attachments**
1. connection creation:
  create connection
2. connection update:
  image
3. getting connection:
  image

### PR DESCRIPTION
**Pull request by lev-titov**

### CODE REVIEW

File: packages/operator/pkg/repository/connection/vault/connection.go [hunk 1]
```diff
@@ -153,6 +153,7 @@ func (vcr *vaultConnRepository) UpdateConnection(conn *connection.Connection) er
 	case err == nil:
 		// If err is not nil, then the connection already exists.
 		existedConn.Spec = conn.Spec
+		existedConn.UpdatedAt = conn.UpdatedAt
```
Comment (keshamin) [inline packages/operator/pkg/repository/connection/vault/connection.go]: All the logic should be removed from repository. The repository is responsible for only saving an object **as is**. Any required checks and modifications should take place on Service level. 
Currently both service and repository make Get request to Vault which is unnecessary.

**Review by keshamin — CHANGES_REQUESTED** [review]

**Review by keshamin — APPROVED** [review]
I implemented the change that I myself requested, so now I approve it.

**Review by BPylypenko — APPROVED** [review]
