### PR TITLE
If Connection.Spec.URI is empty then skip ECR URI specific checks

### LINKED ISSUE #440: ecr conn. tries to validate `uri` param even when I haven't passed it
**description**
when I didn't pass `uri` for `ecr` type conn, I get this error:
`the uri parameter is empty; not valid uri for ecr type: docker-credential-ecr-login can only be used with Amazon Elastic Container Registry.`
for others only: `the uri parameter is empty`

**specification**
[ecr_no_required_parameters.txt](https://github.com/odahu/odahu-flow/files/5607521/ecr_no_required_parameters.txt)

**to reproduce**
1. run `odahuflowctl conn create -f ecr_no_required_parameters.txt`

**Expected behavior**
should show error: `the uri parameter is empty`

**Actual behavior**
shows `the uri parameter is empty; not valid uri for ecr type: docker-credential-ecr-login can only be used with Amazon Elastic Container Registry.`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by vlad-tokarev**
closes #440

### CODE REVIEW

**Review by karbyshevds — APPROVED** [review]

File: packages/operator/pkg/apiserver/routes/v1/connection/connection_validation_test.go [hunk 1]
```diff
@@ -83,6 +83,22 @@ func (s *ConnectionValidationSuite) TestEmptyURL() {
...
+func (s *ConnectionValidationSuite) TestEmptyURLEcr() {
+	conn := &connection.Connection{
+		Spec: v1alpha1.ConnectionSpec{
+			Type:      connection.EcrType,
+			Reference: connReference,
+			KeySecret: creds,
+		},
+	}
+	err := s.v.ValidatesAndSetDefaults(conn)
+	s.g.Expect(err).Should(HaveOccurred())
```
Comment (keshamin) [inline packages/operator/pkg/apiserver/routes/v1/connection/connection_validation_test.go:96]: I remember we discussed that having 2 testing frameworks (gomega + testify) is redundant and further tests we can write with testify. So that we could easier throw gomega away some day.

**Review by keshamin — APPROVED** [review]

File: packages/operator/pkg/apiserver/routes/v1/connection/connection_validation_test.go (hunk 1 above)
Comment (vlad-tokarev) [reply packages/operator/pkg/apiserver/routes/v1/connection/connection_validation_test.go:96]: Yes, I agree, but it's a small fix
