### PR TITLE
Fix Batch Job ID length validation

### LINKED ISSUE #559: fix id validation for Batch Inference
**Description**
1. Since we have a default template for the `InferenceJob id` using the `InferenceService id` in the template: `job-<inference-service-id>-XXXXX`. Hence, the max `InferenceService id` length should be not 63 but 53.
2. Add the validation that the `InferenceJob id` is not more than 63. Now it crashes with an error if it is greater than 64.
And if the length equals 64 characters, it hangs on the "unknown" state.

**Specifications:**
54 chars long `InferenceService id` and related `InferenceJob` (64 chars):
[inference-service-54-chars-id.txt](https://github.com/odahu/odahu-flow/files/6349921/inference-service-54-chars-id.txt)
[inference-job-54-service.txt](https://github.com/odahu/odahu-flow/files/6349922/inference-job-54-service.txt)

55 chars long `InferenceService id` and related `InferenceJob` (65 chars):
[inference-service-55-chars-id.txt](https://github.com/odahu/odahu-flow/files/6349926/inference-service-55-chars-id.txt)
[inference-job-55-service.txt](https://github.com/odahu/odahu-flow/files/6349928/inference-job-55-service.txt)

**Attachments**
`InferenceJob id` length is equal 64 characters:
image
`InferenceJob id` length is more than 64 characters:
image

### PR DESCRIPTION
**Pull request by keshamin**
Since job ID is generated based on service ID, service ID max length is 10 chars less.
Fix #559

### CODE REVIEW

File: packages/operator/pkg/service/batch/service_validate.go [hunk 1]
```diff
@@ -27,12 +27,12 @@ import (
 
 const (
 	EmptySpecFieldErrorMessage = "%s must be non-empty"
+	IDLengthExceeded           = "ID length must be less oe equal to %d"
```
Comment (BPylypenko) [inline packages/operator/pkg/service/batch/service_validate.go]:
```suggestion
	IDLengthExceeded           = "ID length must be less or equal to %d"
```

**Review by BPylypenko — CHANGES_REQUESTED** [review]
Could you, please, also restrict the Job ID to 63 chars as there is a task to add an option to specify the custom InferenceJob ID?

https://github.com/odahu/odahu-flow/issues/568

**Comment by keshamin** [comment]
@BPylypenko 
> Could you, please, also restrict the Job ID to 63 chars as there is a task to add an option to specify the custom InferenceJob ID?
> 
> #568

Will do as a part of that task.

**Review by lev-titov — APPROVED** [review]

**Review by BPylypenko — APPROVED** [review]
